window.cardList = [
  { name: "The Fool", korean_name: "바보", position: "정방향", summary: "연애에 미숙하고 책임감 부족. 깊은 관계로 발전하기 어려우며, 재회 가능성도 낮음." },
  { name: "The Magician", korean_name: "마법사", position: "정방향", summary: "자신감 있고 능력 있는 사람. 끌림은 강하지만 관계는 불안정할 수 있음." },
  { name: "The High Priestess", korean_name: "여교황", position: "정방향", summary: "감정을 드러내지 않으며 신중한 태도. 관계 진전엔 시간이 걸림." },
  { name: "The Empress", korean_name: "여제", position: "정방향", summary: "풍요롭고 다정한 사람. 연애운이 좋고, 결혼 운도 강함." },
  { name: "The Emperor", korean_name: "황제", position: "정방향", summary: "의지가 강하고 주도적인 사람. 믿음직하지만 다소 권위적일 수 있음." },
  { name: "The Hierophant", korean_name: "교황", position: "정방향", summary: "소개로 시작되는 인연. 안정적인 연애로 발전 가능." },
  { name: "The Lovers", korean_name: "연인", position: "정방향", summary: "감정 교류가 풍부하고 로맨틱한 관계. 진지한 만남으로 발전할 수 있음." },
  { name: "The Chariot", korean_name: "전차", position: "정방향", summary: "연애에 대한 열정이 강함. 빠르게 진전될 수 있으나 갈등도 동반될 수 있음." },
  { name: "Strength", korean_name: "힘", position: "정방향", summary: "상대를 감싸주는 사랑. 인내심과 성실함이 돋보이는 관계." },
  { name: "The Hermit", korean_name: "은둔자", position: "정방향", summary: "혼자 있고 싶은 마음이 큼. 새로운 연애보다는 내면을 돌아보는 시기." },
  { name: "Wheel of Fortune", korean_name: "운명의 수레바퀴", position: "정방향", summary: "예기치 않은 인연이나 상황 변화. 긍정적 전환이 일어날 가능성 있음." },
  { name: "Justice", korean_name: "정의", position: "정방향", summary: "감정보다 이성을 우선하는 관계. 결단이 필요한 시점." },
  { name: "The Hanged Man", korean_name: "매달린 사람", position: "정방향", summary: "희생이나 기다림이 필요한 연애. 답답함을 동반할 수 있음." },
  { name: "Death", korean_name: "죽음", position: "정방향", summary: "과거 인연의 종료, 혹은 완전한 전환점. 새로운 만남으로의 계기." },
  { name: "Temperance", korean_name: "절제", position: "정방향", summary: "조화롭고 안정적인 관계. 느리지만 깊게 이어짐." },
  { name: "The Devil", korean_name: "악마", position: "정방향", summary: "강한 유혹이나 집착. 중독적인 관계가 될 수 있음." },
  { name: "The Tower", korean_name: "탑", position: "정방향", summary: "갑작스러운 이별이나 충격. 관계의 근본적 재정비가 필요함." },
  { name: "The Star", korean_name: "별", position: "정방향", summary: "희망이 보이는 관계. 상처 후 회복과 치유의 신호." },
  { name: "The Moon", korean_name: "달", position: "정방향", summary: "혼란스러운 감정선. 진실이 감춰져 있을 수 있음." },
  { name: "The Sun", korean_name: "태양", position: "정방향", summary: "밝고 긍정적인 관계. 결혼운도 강하게 작용할 수 있음." },
  { name: "Judgement", korean_name: "심판", position: "정방향", summary: "재회 가능성이나 과거 관계 정리. 인생의 중요한 기로." },
  { name: "The World", korean_name: "세계", position: "정방향", summary: "완성과 성취. 모든 조건이 맞는 이상적인 관계." },
  { name: "Ace of Wands", korean_name: "완드 에이스", position: "정방향", summary: "완드 에이스 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Two of Wands", korean_name: "완드 2", position: "정방향", summary: "완드 2 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Three of Wands", korean_name: "완드 3", position: "정방향", summary: "완드 3 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Four of Wands", korean_name: "완드 4", position: "정방향", summary: "완드 4 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Five of Wands", korean_name: "완드 5", position: "정방향", summary: "완드 5 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Six of Wands", korean_name: "완드 6", position: "정방향", summary: "완드 6 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Seven of Wands", korean_name: "완드 7", position: "정방향", summary: "완드 7 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Eight of Wands", korean_name: "완드 8", position: "정방향", summary: "완드 8 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Nine of Wands", korean_name: "완드 9", position: "정방향", summary: "완드 9 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Ten of Wands", korean_name: "완드 10", position: "정방향", summary: "완드 10 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Page of Wands", korean_name: "완드 시종", position: "정방향", summary: "완드 시종 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Knight of Wands", korean_name: "완드 기사", position: "정방향", summary: "완드 기사 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Queen of Wands", korean_name: "완드 여왕", position: "정방향", summary: "완드 여왕 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "King of Wands", korean_name: "완드 왕", position: "정방향", summary: "완드 왕 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Ace of Cups", korean_name: "컵 에이스", position: "정방향", summary: "컵 에이스 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Two of Cups", korean_name: "컵 2", position: "정방향", summary: "컵 2 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Three of Cups", korean_name: "컵 3", position: "정방향", summary: "컵 3 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Four of Cups", korean_name: "컵 4", position: "정방향", summary: "컵 4 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Five of Cups", korean_name: "컵 5", position: "정방향", summary: "컵 5 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Six of Cups", korean_name: "컵 6", position: "정방향", summary: "컵 6 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Seven of Cups", korean_name: "컵 7", position: "정방향", summary: "컵 7 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Eight of Cups", korean_name: "컵 8", position: "정방향", summary: "컵 8 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Nine of Cups", korean_name: "컵 9", position: "정방향", summary: "컵 9 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Ten of Cups", korean_name: "컵 10", position: "정방향", summary: "컵 10 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Page of Cups", korean_name: "컵 시종", position: "정방향", summary: "컵 시종 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Knight of Cups", korean_name: "컵 기사", position: "정방향", summary: "컵 기사 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Queen of Cups", korean_name: "컵 여왕", position: "정방향", summary: "컵 여왕 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "King of Cups", korean_name: "컵 왕", position: "정방향", summary: "컵 왕 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Ace of Swords", korean_name: "소드 에이스", position: "정방향", summary: "소드 에이스 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Two of Swords", korean_name: "소드 2", position: "정방향", summary: "소드 2 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Three of Swords", korean_name: "소드 3", position: "정방향", summary: "소드 3 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Four of Swords", korean_name: "소드 4", position: "정방향", summary: "소드 4 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Five of Swords", korean_name: "소드 5", position: "정방향", summary: "소드 5 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Six of Swords", korean_name: "소드 6", position: "정방향", summary: "소드 6 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Seven of Swords", korean_name: "소드 7", position: "정방향", summary: "소드 7 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Eight of Swords", korean_name: "소드 8", position: "정방향", summary: "소드 8 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Nine of Swords", korean_name: "소드 9", position: "정방향", summary: "소드 9 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Ten of Swords", korean_name: "소드 10", position: "정방향", summary: "소드 10 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Page of Swords", korean_name: "소드 시종", position: "정방향", summary: "소드 시종 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Knight of Swords", korean_name: "소드 기사", position: "정방향", summary: "소드 기사 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Queen of Swords", korean_name: "소드 여왕", position: "정방향", summary: "소드 여왕 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "King of Swords", korean_name: "소드 왕", position: "정방향", summary: "소드 왕 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Ace of Pentacles", korean_name: "펜타클 에이스", position: "정방향", summary: "펜타클 에이스 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Two of Pentacles", korean_name: "펜타클 2", position: "정방향", summary: "펜타클 2 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Three of Pentacles", korean_name: "펜타클 3", position: "정방향", summary: "펜타클 3 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Four of Pentacles", korean_name: "펜타클 4", position: "정방향", summary: "펜타클 4 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Five of Pentacles", korean_name: "펜타클 5", position: "정방향", summary: "펜타클 5 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Six of Pentacles", korean_name: "펜타클 6", position: "정방향", summary: "펜타클 6 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Seven of Pentacles", korean_name: "펜타클 7", position: "정방향", summary: "펜타클 7 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Eight of Pentacles", korean_name: "펜타클 8", position: "정방향", summary: "펜타클 8 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Nine of Pentacles", korean_name: "펜타클 9", position: "정방향", summary: "펜타클 9 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Ten of Pentacles", korean_name: "펜타클 10", position: "정방향", summary: "펜타클 10 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Page of Pentacles", korean_name: "펜타클 시종", position: "정방향", summary: "펜타클 시종 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Knight of Pentacles", korean_name: "펜타클 기사", position: "정방향", summary: "펜타클 기사 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "Queen of Pentacles", korean_name: "펜타클 여왕", position: "정방향", summary: "펜타클 여왕 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
  { name: "King of Pentacles", korean_name: "펜타클 왕", position: "정방향", summary: "펜타클 왕 카드입니다. 상황에 따라 다양한 해석이 필요해요." },
];

