const cardList = [
  { name: "The Fool", korean_name: "바보", position: "정방향", summary: "연애에 미숙하고 책임감 부족. 깊은 관계로 발전하기 어려우며, 재회 가능성도 낮음." },
  { name: "The Magician", korean_name: "마법사", position: "정방향", summary: "자신감 있고 능력 있는 사람. 끌림은 강하지만 관계는 불안정할 수 있음." },
  { name: "The High Priestess", korean_name: "여교황", position: "정방향", summary: "감정을 드러내지 않으며 신중한 태도. 관계 진전엔 시간이 걸림." },
  { name: "The Empress", korean_name: "여제", position: "정방향", summary: "풍요롭고 다정한 사람. 연애운이 좋고, 결혼 운도 강함." },
  { name: "The Emperor", korean_name: "황제", position: "정방향", summary: "의지가 강하고 주도적인 사람. 믿음직하지만 다소 권위적일 수 있음." },
  { name: "The Hierophant", korean_name: "교황", position: "정방향", summary: "소개로 시작되는 인연. 안정적인 연애로 발전 가능." },
  { name: "The Lovers", korean_name: "연인", position: "정방향", summary: "감정 교류가 풍부하고 로맨틱한 관계. 진지한 만남으로 발전할 수 있음." },
  { name: "The Chariot", korean_name: "전차", position: "정방향", summary: "연애에 대한 열정이 강함. 빠르게 진전될 수 있으나 갈등도 동반될 수 있음." },
  { name: "Strength", korean_name: "힘", position: "정방향", summary: "상대를 감싸주는 사랑. 인내심과 성실함이 돋보이는 관계." },
  { name: "The Hermit", korean_name: "은둔자", position: "정방향", summary: "혼자 있고 싶은 마음이 큼. 새로운 연애보다는 내면을 돌아보는 시기." },
  { name: "Wheel of Fortune", korean_name: "운명의 수레바퀴", position: "정방향", summary: "예기치 않은 인연이나 상황 변화. 긍정적 전환이 일어날 가능성 있음." },
  { name: "Justice", korean_name: "정의", position: "정방향", summary: "감정보다 이성을 우선하는 관계. 결단이 필요한 시점." },
  { name: "The Hanged Man", korean_name: "매달린 사람", position: "정방향", summary: "희생이나 기다림이 필요한 연애. 답답함을 동반할 수 있음." },
  { name: "Death", korean_name: "죽음", position: "정방향", summary: "과거 인연의 종료, 혹은 완전한 전환점. 새로운 만남으로의 계기." },
  { name: "Temperance", korean_name: "절제", position: "정방향", summary: "조화롭고 안정적인 관계. 느리지만 깊게 이어짐." },
  { name: "The Devil", korean_name: "악마", position: "정방향", summary: "강한 유혹이나 집착. 중독적인 관계가 될 수 있음." },
  { name: "The Tower", korean_name: "탑", position: "정방향", summary: "갑작스러운 이별이나 충격. 관계의 근본적 재정비가 필요함." },
  { name: "The Star", korean_name: "별", position: "정방향", summary: "희망이 보이는 관계. 상처 후 회복과 치유의 신호." },
  { name: "The Moon", korean_name: "달", position: "정방향", summary: "혼란스러운 감정선. 진실이 감춰져 있을 수 있음." },
  { name: "The Sun", korean_name: "태양", position: "정방향", summary: "밝고 긍정적인 관계. 결혼운도 강하게 작용할 수 있음." },
  { name: "Judgement", korean_name: "심판", position: "정방향", summary: "재회 가능성이나 과거 관계 정리. 인생의 중요한 기로." },
  { name: "The World", korean_name: "세계", position: "정방향", summary: "완성과 성취. 모든 조건이 맞는 이상적인 관계." },
  { name: "Ace of Wands", korean_name: "완드 에이스", position: "정방향", summary: "열정과 창의력, 새로운 시작의 불꽃이 피어나는 시점" },
  { name: "Two of Wands", korean_name: "완드 2", position: "정방향", summary: "계획과 선택의 기로, 더 넓은 세상에 대한 탐색" },
  { name: "Three of Wands", korean_name: "완드 3", position: "정방향", summary: "기회를 기다리는 기대감, 확장의 시기" },
  { name: "Four of Wands", korean_name: "완드 4", position: "정방향", summary: "안정과 축하의 시간, 공동체 속의 조화" },
  { name: "Five of Wands", korean_name: "완드 5", position: "정방향", summary: "의견 충돌이나 경쟁, 성장 과정의 갈등" },
  { name: "Six of Wands", korean_name: "완드 6", position: "정방향", summary: "승리와 인정, 대중의 주목을 받는 시기" },
  { name: "Seven of Wands", korean_name: "완드 7", position: "정방향", summary: "자기 입장을 지키려는 방어적 태도" },
  { name: "Eight of Wands", korean_name: "완드 8", position: "정방향", summary: "빠르게 흘러가는 상황, 메시지 도착" },
  { name: "Nine of Wands", korean_name: "완드 9", position: "정방향", summary: "지치지만 포기하지 않는 인내심" },
  { name: "Ten of Wands", korean_name: "완드 10", position: "정방향", summary: "무거운 짐과 책임감, 버거운 상황" },
  { name: "Page of Wands", korean_name: "완드 시종", position: "정방향", summary: "새로운 아이디어와 창의적 시도" },
  { name: "Knight of Wands", korean_name: "완드 기사", position: "정방향", summary: "열정적으로 밀어붙이는 에너지" },
  { name: "Queen of Wands", korean_name: "완드 여왕", position: "정방향", summary: "자신감과 매력, 주체적인 태도" },
  { name: "King of Wands", korean_name: "완드 왕", position: "정방향", summary: "비전과 리더십으로 이끄는 존재" },
  { name: "Ace of Cups", korean_name: "컵 에이스", position: "정방향", summary: "감정의 시작, 사랑과 연결의 탄생" },
  { name: "Two of Cups", korean_name: "컵 2", position: "정방향", summary: "사랑과 상호 이해, 파트너십 형성" },
  { name: "Three of Cups", korean_name: "컵 3", position: "정방향", summary: "축하와 우정, 즐거운 관계" },
  { name: "Four of Cups", korean_name: "컵 4", position: "정방향", summary: "권태와 무관심, 새로운 기회 간과" },
  { name: "Five of Cups", korean_name: "컵 5", position: "정방향", summary: "실망과 후회, 잃은 것에 대한 슬픔" },
  { name: "Six of Cups", korean_name: "컵 6", position: "정방향", summary: "추억과 회상, 과거의 감정" },
  { name: "Seven of Cups", korean_name: "컵 7", position: "정방향", summary: "환상과 선택, 현실 감각의 필요" },
  { name: "Eight of Cups", korean_name: "컵 8", position: "정방향", summary: "감정적 거리 두기, 떠남과 포기" },
  { name: "Nine of Cups", korean_name: "컵 9", position: "정방향", summary: "감정적 만족과 소망 성취" },
  { name: "Ten of Cups", korean_name: "컵 10", position: "정방향", summary: "가족과 관계의 조화로운 행복" },
  { name: "Page of Cups", korean_name: "컵 시종", position: "정방향", summary: "순수한 감정, 사랑스러운 제안" },
  { name: "Knight of Cups", korean_name: "컵 기사", position: "정방향", summary: "로맨틱한 접근과 감정 표현" },
  { name: "Queen of Cups", korean_name: "컵 여왕", position: "정방향", summary: "공감과 직관, 감정적인 안정감" },
  { name: "King of Cups", korean_name: "컵 왕", position: "정방향", summary: "성숙한 감정 조절과 배려" },
  { name: "Ace of Swords", korean_name: "소드 에이스", position: "정방향", summary: "진실의 시작, 명확한 통찰과 결단" },
  { name: "Two of Swords", korean_name: "소드 2", position: "정방향", summary: "선택의 갈등, 이성과 감정 사이" },
  { name: "Three of Swords", korean_name: "소드 3", position: "정방향", summary: "상처와 배신, 이별의 아픔" },
  { name: "Four of Swords", korean_name: "소드 4", position: "정방향", summary: "휴식과 회복, 내면의 안정 필요" },
  { name: "Five of Swords", korean_name: "소드 5", position: "정방향", summary: "이기심으로 인한 갈등과 불편함" },
  { name: "Six of Swords", korean_name: "소드 6", position: "정방향", summary: "변화와 이동, 마음의 치유" },
  { name: "Seven of Swords", korean_name: "소드 7", position: "정방향", summary: "속임수나 비밀, 뒤에서 벌어지는 일" },
  { name: "Eight of Swords", korean_name: "소드 8", position: "정방향", summary: "두려움과 제한, 스스로 만든 감금" },
  { name: "Nine of Swords", korean_name: "소드 9", position: "정방향", summary: "불면과 불안, 정신적 고통" },
  { name: "Ten of Swords", korean_name: "소드 10", position: "정방향", summary: "끝장난 상황, 배신과 절망" },
  { name: "Page of Swords", korean_name: "소드 시종", position: "정방향", summary: "날카로운 관찰력과 탐색의 시작" },
  { name: "Knight of Swords", korean_name: "소드 기사", position: "정방향", summary: "빠른 실행력과 돌진하는 행동" },
  { name: "Queen of Swords", korean_name: "소드 여왕", position: "정방향", summary: "이성적이고 냉철한 판단력" },
  { name: "King of Swords", korean_name: "소드 왕", position: "정방향", summary: "공정한 리더십과 전략적 사고" },
  { name: "Ace of Pentacles", korean_name: "펜타클 에이스", position: "정방향", summary: "현실적 기회의 시작, 재물운 상승" },
  { name: "Two of Pentacles", korean_name: "펜타클 2", position: "정방향", summary: "균형 감각, 여러 일을 유연하게 처리" },
  { name: "Three of Pentacles", korean_name: "펜타클 3", position: "정방향", summary: "협력과 공동의 성과, 팀워크" },
  { name: "Four of Pentacles", korean_name: "펜타클 4", position: "정방향", summary: "소유욕과 안정 추구, 움켜쥠" },
  { name: "Five of Pentacles", korean_name: "펜타클 5", position: "정방향", summary: "경제적 어려움, 외로움과 상실" },
  { name: "Six of Pentacles", korean_name: "펜타클 6", position: "정방향", summary: "나눔과 균형, 도움 주거나 받기" },
  { name: "Seven of Pentacles", korean_name: "펜타클 7", position: "정방향", summary: "노력에 대한 성찰, 기다림의 시기" },
  { name: "Eight of Pentacles", korean_name: "펜타클 8", position: "정방향", summary: "기술 연마, 꾸준한 노력" },
  { name: "Nine of Pentacles", korean_name: "펜타클 9", position: "정방향", summary: "자립과 안정, 우아한 삶" },
  { name: "Ten of Pentacles", korean_name: "펜타클 10", position: "정방향", summary: "재산과 유산, 가문의 풍요" },
  { name: "Page of Pentacles", korean_name: "펜타클 시종", position: "정방향", summary: "학습과 현실적 계획의 시작" },
  { name: "Knight of Pentacles", korean_name: "펜타클 기사", position: "정방향", summary: "성실함과 끈기, 느리지만 꾸준함" },
  { name: "Queen of Pentacles", korean_name: "펜타클 여왕", position: "정방향", summary: "가정과 일의 균형, 실용적인 도움" },
  { name: "King of Pentacles", korean_name: "펜타클 왕", position: "정방향", summary: "부와 권위를 갖춘 안정적 존재" }
];

export default cardList;
